export const seedData = [
  {
    "supplier": "Episaveur - Épicerie",
    "products": [
      "Info : Lundi matin au plus tard pour mardi",
      "Épicerie",
      "Sel fin",
      "Gros sel",
      "Poivre noir mignonnette",
      "Poivre noir moulu",
      "Poivre en graines",
      "Cumin en poudre",
      "Piment d’Espelette",
      "Farine T55",
      "Farine de riz",
      "Origan",
      "Thym",
      "Herbes de Provence",
      "Noix",
      "Pain de mie",
      "Miel",
      "Artichaut confit à l'huile",
      "Gidolive",
      "L'huile de pepin de raisin",
      "L'huile de colza",
      "L'huile de friteuse",
      "l'huile de sésame",
      "Ketchup en bidon de 5 l",
      "Mayonnaise seau 5L",
      "Câpres",
      "Cornichons",
      "Olive noir",
      "Olive verte",
      "Maizena",
      "Moutarde à l'ancienne",
      "Moutarde de Dijon",
      "Jus de porc Knorr",
      "Fond de volaille",
      "Arôme patrelle",
      "Riz",
      "Semoule couscous",
      "Tagliatelles",
      "Sauce soja salé",
      "Sauce soja sucré",
      "Maïs",
      "Escargots de Bourgogne",
      "Crème balsamique",
      "Vinaigre balsamique 5 L",
      "Porto",
      "Vinaigre blanc",
      "Tabasco",
      "Sauce worcester",
      "Cacahuètes",
      "Mini ketchup",
      "Mini mayonnaise",
      "Mini moutarde",
      "Sel de céleri",
      "Mini tabasco 65 cl",
      "Jus de citron jaune 1L",
      "Jus de citron vert 1 L",
      "Rince doigt",
      "Poire en sirop",
      "Vanille artificielle",
      "Vanille en pâte",
      "Boudoir tiramisu",
      "Pépites de chocolat",
      "Poudre d'amande",
      "Poudre à crème chaud",
      "Feuille de gélatine",
      "Bombe à graisse",
      "Poches sous vide",
      "Pois chiche",
      "Tahini",
      "Velour noir alimentaire",
      "Les gavottes",
      "Piment pour la chimichurri",
      "Baie de genievre",
      "Laurier",
      "Eau gazeuse",
      "Vin blanc cubi cuisine 10 L",
      "Sucre en buchette",
      "Raisin sec",
      "Café moulu pas chère tiramisu",
      "Piquillos",
      "Tomates confites",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Episaveur - Entretien",
    "products": [
      "Info : Lundi matin au plus tard pour mardi",
      "Entretien / consommables",
      "Film alimentaire",
      "Papier cuisson",
      "Poches à douilles",
      "Papier essuie tout cuisine",
      "Tork en tissu cuisine",
      "Gants M",
      "Gants L",
      "Éponges vertes",
      "Pailles en fer",
      "Lavette ajourée bleu",
      "Sac poubelles 130 L",
      "Produit plonge manuelle",
      "Produit vaisselle cuisine",
      "Produit de rinçage",
      "Produit lave verre",
      "Produit désinfectant cuisine",
      "Papier imprimante",
      "Papier TPE",
      "Papier toilette",
      "Papier essuie main sanitaires",
      "Serviette petit format noir",
      "Produit plancha",
      "Produit sol cuisine",
      "Dégraisseur cuisine pulvérisateur",
      "Mousse lavante main",
      "Produit nettoyage salle en pulvérisateur",
      "Raclette",
      "Manche à raclette",
      "Pulvirisateurs",
      "Serviettes kengouru",
      "Produit de nettoyage easy all bidon 5 L",
      "Papier toilette mini 110 mètres Global Hygiene",
      "Produit nettoyage toilette",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Passion Froid",
    "products": [
      "Info : Lundi pour mardi / mercredi pour jeudi",
      "BOF",
      "Micro-beurre",
      "Lait entier",
      "Lait demi-écremé",
      "Burratina",
      "Parmesan",
      "Emmental",
      "Roquefort",
      "Gorgonzolla",
      "Faiselle 6 % 500 G",
      "Crème fraiche épaisse 30 %",
      "Mascarpone",
      "FRAIS",
      "Tartare de tomate",
      "Saucisses hot-dog",
      "Bavette",
      "Saucisson sec",
      "Rosette",
      "Andouille",
      "Lardons fumé",
      "Truite fumé",
      "SURGELÉ",
      "Pain hot-dog",
      "Échalotes ciselé",
      "Persil haché",
      "Pesto",
      "Framboise surgelé",
      "Choux craquelin",
      "Tartes aux pomme",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Terre Azur",
    "products": [
      "Info : Commandes mardi / jeudi / samedi",
      "Agrumes / herbes",
      "Citron vert",
      "Menthe",
      "Oranges",
      "Pamplemousse",
      "Fruit de la passion",
      "Romarin frais",
      "Purées de fruits frais",
      "Purée de fruit rouge",
      "Segments d'agrumes",
      "Purée d'abricot",
      "Herbes",
      "Ciboulette",
      "Estragon",
      "Cerfeuil",
      "Persil",
      "Oignons nouveau botte",
      "Oignons rouge",
      "Oignon jaune",
      "Salades",
      "Salade cœur de romaine",
      "Roquette",
      "Batavia",
      "Feuille de chêne rouge",
      "Laitue",
      "Fruits",
      "Pomme golden",
      "Fraises",
      "Myrtille",
      "Melon",
      "Citron jaune",
      "Légumes",
      "Concombre",
      "Tomates cocktail grappes",
      "Radis read meat",
      "Radis",
      "Haricots verts",
      "Céleri branches",
      "Brocoli",
      "Choux pak choï",
      "Pois mange tout",
      "Carotte orange",
      "Champignons de Paris",
      "Autre",
      "Frites fraîches",
      "Moules",
      "Tomates confites cerise",
      "Ail pelé en boite",
      "Écrevisses",
      "Filet d'anchois",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Olivier Brosset",
    "products": [
      "Info : Lundi pour mercredi / mercredi pour vendredi",
      "Produits",
      "Blanc de poulet cuit nature",
      "Mini-rillauds",
      "Saucissons à l'ail",
      "Terrine de grande mère",
      "Bacon",
      "Poulets pour le perso",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Compagnie des Desserts",
    "products": [
      "Info : Lundi pour mardi / jeudi pour vendredi",
      "CREMES GLACEES",
      "Vanille Bourbon",
      "Chocolat",
      "Yaourt Bulgare",
      "Café des Indes",
      "Spéculoos",
      "Barbe à papa",
      "Menthe Chocolat",
      "SORBETS",
      "Noix de coco",
      "Fraise",
      "Orange",
      "Abricot",
      "Cassis",
      "Citron jaune",
      "Framboise",
      "Pêche de vigne",
      "Fruit de la passion",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Miko",
    "products": [
      "Info : Mardi pour mercredi",
      "Produits",
      "Confit de canard",
      "Oignons Grelot",
      "Cordon bleu",
      "Crème Liquide 18%",
      "Glace Haribo enfant",
      "Rinces doigt",
      "Crème liquide 35 % dépannage",
      "Mascarpone",
      "Poulet corn flex 20/90 g",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Sysco",
    "products": [
      "Info : Vendredi pour lundi / mercredi pour jeudi",
      "Produits",
      "Beurre doux",
      "Beurre demi sel",
      "Camemebert à rôtir",
      "Jaune d'œuf",
      "Crème liquide 35 %",
      "Crème liquide 18 %",
      "Friture de Joël",
      "Escargot de Bourgogne",
      "Carpaccio de bœuf",
      "Mortadelle",
      "Poivrions piquillos 3/1",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Mavel",
    "products": [
      "Info : Lundi pour mardi",
      "Produits",
      "Grenailles chair ferme",
      "Carotte orange",
      "Oignons rouge",
      "Oignon jaune",
      "Échalote",
      "Légumes verts en promo",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "JA Gastro",
    "products": [
      "Info : Lundi / mercredi",
      "Produits",
      "Jambon fumé de Montagne",
      "Viande à Tartare",
      "Paleron de cochon",
      "Andouillette au Saumur Champigny",
      "Fuseau - Mardi",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Fuseau",
    "products": [
      "Info : Mardi",
      "Produits",
      "Chocolat 50 % couverture 10 KG",
      "Chocolat en pépite 45 % sac 20 kg",
      "Sucre en poudre",
      "Sucre glace",
      "Sucre inverti",
      "Sucre canonnade",
      "Amandes effilé",
      "Œufs",
      "Blanc d'œufs",
      "Crème fraîche",
      "Mascarpone",
      "Surgelé",
      "Purée de fruit rouge",
      "Purée de pastéque",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Fromagerie Gireaud",
    "products": [
      "Info : Mercredi ou jeudi",
      "Fromages",
      "Burrata",
      "Brie de maux",
      "Compté jeune 10 mois",
      "Compté fruité 12 à 18 mois",
      "Compté réserve 24 à 36 mois",
      "Fêta",
      "Fromage faisselle",
      "Mozzarella",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Ange et Loup",
    "products": [
      "Info : Mardi",
      "Fromages de chèvre",
      "Crottins de chèvre",
      "Chèvre cendré",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Boulangeries   Pain",
    "products": [
      "Boulangeries / Pain",
      "Info : Selon besoin",
      "Produits",
      "Miroirs de Loire / Boulangerie Roseraie",
      "Boulangerie de St Saturnin - pain de maïs/complet",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "DPAP",
    "products": [
      "Info : Selon besoin",
      "Produits",
      "Tartare de saumon fumé",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "ELIS",
    "products": [
      "Info : Selon besoin",
      "Linge",
      "Torchons",
      "Tabliers",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  },
  {
    "supplier": "Hennequin - Poissonnier",
    "products": [
      "Info : Toutes les 2 semaines",
      "Poisson",
      "Anguilles",
      "Sandre",
      "Cuisses des grenouilles",
      "Commande envoyée : ____      Livraison prévue : ____"
    ]
  }
];
